"""phase2 initial schema

Revision ID: d522c7da2351
Revises: 
Create Date: 2026-09-27 16:43:33.660569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd522c7da2351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('code', name=op.f('uq_groups_code'))
    )
    op.create_table('report_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_fa', sa.String(length=128), nullable=False),
    sa.Column('is_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_types')),
    sa.UniqueConstraint('code', name=op.f('uq_report_types_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label_fa', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_code', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_equipment_group_id_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('equipment_code', name=op.f('uq_equipment_equipment_code'))
    )
    op.create_index(op.f('ix_equipment_group_id'), 'equipment', ['group_id'], unique=False)
    op.create_table('report_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('jalali_year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_report_sequences_group_id_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_sequences')),
    sa.UniqueConstraint('group_id', 'jalali_year', name='uq_report_sequences_group_year')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('report_type_id', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_jalali_year', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_reports_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_reports_group_id_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name=op.f('fk_reports_locked_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_types.id'], name=op.f('fk_reports_report_type_id_report_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('report_number', name=op.f('uq_reports_report_number'))
    )
    op.create_index(op.f('ix_reports_created_by'), 'reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_reports_equipment_id'), 'reports', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reports_event_datetime'), 'reports', ['event_datetime'], unique=False)
    op.create_index(op.f('ix_reports_group_id'), 'reports', ['group_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups')),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_groups_user_group')
    )
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_user_id'), 'user_groups', ['user_id'], unique=False)
    op.create_table('report_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_participants_report_id_reports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_participants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_participants'))
    )
    op.create_index(op.f('ix_report_participants_report_id'), 'report_participants', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_participants_user_id'), 'report_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed data: DB-driven roles and report types (spec sections 4, 13) ---
    roles_table = sa.table(
        'roles',
        sa.column('code', sa.String),
        sa.column('label_fa', sa.String),
    )
    op.bulk_insert(roles_table, [
        {'code': 'USER', 'label_fa': 'کاربر'},
        {'code': 'EXPERT', 'label_fa': 'کارشناس'},
        {'code': 'MANAGEMENT', 'label_fa': 'مدیریت'},
        {'code': 'AUDITOR', 'label_fa': 'بازرس ارشد'},
    ])

    report_types_table = sa.table(
        'report_types',
        sa.column('code', sa.String),
        sa.column('name_fa', sa.String),
        sa.column('is_failure', sa.Boolean),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(report_types_table, [
        {'code': 'MINOR_FAILURE_REPAIR', 'name_fa': 'تعمیر خرابی جزئی', 'is_failure': True, 'is_active': True},
        {'code': 'MAJOR_FAILURE_REPAIR', 'name_fa': 'تعمیر خرابی عمده', 'is_failure': True, 'is_active': True},
        {'code': 'PERIODIC_SERVICE', 'name_fa': 'سرویس دوره‌ای', 'is_failure': False, 'is_active': True},
        {'code': 'INSPECTION_VISIT', 'name_fa': 'بازدید / بازرسی', 'is_failure': False, 'is_active': True},
    ])

    system_settings_table = sa.table(
        'system_settings',
        sa.column('key', sa.String),
        sa.column('value', sa.String),
        sa.column('description', sa.String),
    )
    op.bulk_insert(system_settings_table, [
        {
            'key': 'REPORT_EDIT_WINDOW_HOURS',
            'value': '24',
            'description': 'Hours a USER may edit their own report after creation (spec section 18).',
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_participants_user_id'), table_name='report_participants')
    op.drop_index(op.f('ix_report_participants_report_id'), table_name='report_participants')
    op.drop_table('report_participants')
    op.drop_index(op.f('ix_user_groups_user_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_reports_group_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_event_datetime'), table_name='reports')
    op.drop_index(op.f('ix_reports_equipment_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_by'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('report_sequences')
    op.drop_index(op.f('ix_equipment_group_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('roles')
    op.drop_table('report_types')
    op.drop_table('groups')
    # ### end Alembic commands ###
